
set VULKAN_SDK_PATH=C:\VulkanSDK
set VULKAN_SDK_VERSION=1.2.148.1

set VULKAN_SHADER_COMPILER=%VULKAN_SDK_PATH%\%VULKAN_SDK_VERSION%\Bin\glslc.exe

set VERTEX_SHADER=shader
set FRAGMENT_SHADER=shader

set SECOND_SHADER=Second

%VULKAN_SHADER_COMPILER% %VERTEX_SHADER%.vert -o vs_%VERTEX_SHADER%.spv
%VULKAN_SHADER_COMPILER% %FRAGMENT_SHADER%.frag -o fs_%FRAGMENT_SHADER%.spv

%VULKAN_SHADER_COMPILER% %SECOND_SHADER%.vert -o vs_%SECOND_SHADER%.spv
%VULKAN_SHADER_COMPILER% %SECOND_SHADER%.frag -o fs_%SECOND_SHADER%.spv

pause